
module.exports = {
  "APIUser": "anypayinc",
  "UserName": "anypayinc",
  "RegistrantFirstName": "ANYPAY",
  "RegistrantLastName": "INC.",
  "RegistrantAddress1": "110 State St",
  "RegistrantAddress2": "1",
  "RegistrantCity": "Portsmouth",
  "RegistrantStateProvince": "NH",
  "RegistrantPostalCode": "03801",
  "RegistrantCountry": "US",
  "RegistrantPhone": "+1.4154072789",
  "RegistrantEmailAddress": "steven@anypayinc.com",
  "TechFirstName": "Steven",
  "TechLastName": "Zeiler",
  "TechAddress1": "110 State St",
  "TechAddress2": "1",
  "TechCity": "Portsmouth",
  "TechStateProvince": "NH",
  "TechPostalCode": "03801",
  "TechCountry": "US",
  "TechPhone": "+1.4154072789",
  "TechEmailAddress": "steven@anypayinc.com",
  "AdminFirstName": "Steven",
  "AdminLastName": "Zeiler",
  "AdminAddress1": "110 State St",
  "AdminAddress2": "1",
  "AdminCity": "Portsmouth",
  "AdminStateProvince": "NH",
  "AdminPostalCode": "03801",
  "AdminCountry": "US",
  "AdminPhone": "+1.4154072789",
  "AdminEmailAddress": "steven@anypayinc.com",
  "AuxBillingFirstName": "Steven",
  "AuxBillingLastName": "Zeiler",
  "AuxBillingAddress1": "110 State St",
  "AuxBillingAddress2": "1",
  "AuxBillingCity": "Portsmouth",
  "AuxBillingStateProvince": "NH",
  "AuxBillingPostalCode": "03801",
  "AuxBillingCountry": "US",
  "AuxBillingPhone": "+1.4154072789",
  "AuxBillingEmailAddress": "steven@anypayinc.com"
};

